parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $redisHost: '%env(REDIS_HOST)%'
            $redisPort: '%env(REDIS_PORT)%'
            $defaultTtlSeconds: '%env(REDIS_DEFAULT_TTL)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\src\:
        resource: '../../../src/*'
