version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - symfony

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
