nelmio_api_doc:
    documentation:
        info:
            title: Book Microservice API
            description: API for managing books in the library
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas:
        default:
            path_patterns:
                - ^/books
                - ^/healthcheck